export default {
	b: { bold: true },
	strong: { bold: true },
	u: { decoration: "underline" },
	s: { decoration: "lineThrough" },
	em: { italics: true },
	i: { italics: true },
	h1: {
		fontSize: 30,
		bold: true,
		alignment: "center",
		color: "#000",
		lineHeight: 1.25,
		margin: [10, 10, 0, 10],
	},
	h2: {
		fontSize: 25,
		bold: true,
		marginBottom: 5,
		background: "#ccc",
		align: "center",
	},
	h3: { fontSize: 20, bold: true, marginBottom: 5 },
	h4: { fontSize: 18, bold: true, marginBottom: 5 },
	h5: { fontSize: 16, bold: true, marginBottom: 5 },
	h6: { fontSize: 14, bold: true, marginBottom: 5 },
	a: { color: "blue", decoration: "" },
	strike: { decoration: "lineThrough" },
	p: { margin: [0, 5, 0, 10] },
	ul: { marginBottom: 5 },
	li: { marginLeft: 5 },
	table: { marginBottom: 5 },
	th: { bold: true, fillColor: "#EEEEEE" },
};
//JS doesn't import JSON yet
